# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170510_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.Place'),
        ),
    ]
