# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='column_name', max_length=50)),
            ],
        ),
    ]
