# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_test_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friends', models.ManyToManyField(related_name='_person2_friends_+', to='news.Person2')),
            ],
        ),
    ]
