# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_author_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
